[project]
name = "sip"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "ping3>=4.0.8",
    "selenium>=4.34.2",
]
