# https://docs.n8n.io/hosting/
name: n8n

services:
  n8n:
    stdin_open: true
    tty: true
    container_name: n8n
    ports:
      - 5678:5678
    volumes:
      - data:/home/node/.n8n
    image: docker.n8n.io/n8nio/n8n
volumes:
  data:
